// src/settings/views/Settings.tsx
import { Button, Card, Form, Input, Layout, PageHeader } from 'antd';
import { FormComponentProps } from 'antd/lib/form';
import { WrappedFormUtils } from 'antd/lib/form/Form';
import React, { useCallback } from 'react';

import RemoteLink from '@src/components/RemoteLink';
import { useAction, useStoreState } from '@src/store';
import { ICustomSettings } from '@typings/index';
import { actions } from '../store';
import styles from './Settings.module.scss';


const GOOGLE_API_WIZARD_URL =
  'https://console.cloud.google.com/apis/credentials/wizard?api=translate.googleapis.com';

const Settings: React.FC = () => {
  const settings = useStoreState(state => state.settings.settings);
  const saveSettings = useAction(actions.saveSettings);

  const handleSubmit = useCallback(
    (e: React.FormEvent, form: WrappedFormUtils<ICustomSettings>) => {
      e.preventDefault();

      form.validateFields((err, values) => {
        saveSettings(values);
      });
    },
    [saveSettings]);

  return (
    <Layout>
      <Layout.Content>
        <Card
          className={styles.Card}
          title={<PageHeader title="Settings" onBack={() => window.history.back()}/>}
        >
          <WrappedSettingsForm settings={settings} onSubmit={handleSubmit}/>
        </Card>
      </Layout.Content>
    </Layout>
  );
};

export default Settings;

interface ISettingsFormProps extends FormComponentProps {
  settings: ICustomSettings;
  onSubmit: (e: React.FormEvent, form: WrappedFormUtils<ICustomSettings>) => void;
}

const SettingsForm: React.FC<ISettingsFormProps> = ({form, settings, onSubmit}) => {
  const {getFieldDecorator} = form;

  return (
    <Form onSubmit={e => onSubmit(e, form)}>
      <Form.Item
        label="Google Translate™ API Key"
        help={<RemoteLink href={GOOGLE_API_WIZARD_URL}/>}
      >
        {getFieldDecorator(
          'googleTranslateApiKey',
          {initialValue: settings.googleTranslateApiKey},
        )(<Input/>)}
      </Form.Item>

      <Form.Item className={styles.FormActions}>
        <Button type="danger" ghost htmlType="reset" onClick={() => window.history.back()}>
          Cancel
        </Button>
        <Button type="primary" htmlType="submit">
          Save
        </Button>
      </Form.Item>
    </Form>
  );
};

const WrappedSettingsForm = Form.create<ISettingsFormProps>({name: 'settings'})(SettingsForm);

// __src/app/views/settings/settings.component.ts
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { FormControl, FormGroup} from '@angular/forms';
import { SettingsService } from '@app/services/settings.service';

@Component({
  selector: 'app-settings',
  templateUrl: './settings.component.html',
  styleUrls: ['./settings.component.scss']
})
export class SettingsComponent implements OnInit {
  settings = new FormGroup({
    googleTranslateApiKey: new FormControl(''),
  });

  originalSettings: any;

  translateApiKeyLink = 'https://console.cloud.google.com/apis/credentials/wizard?api=translate.googleapis.com';

  constructor(
    private settingsService: SettingsService,
    private location: Location,
  ) {
  }

  ngOnInit() {
    this.settingsService.getSettings().subscribe((data) => {
      this.originalSettings = data;
      this.settings.patchValue(data);
    });
  }

  saveSettings(event) {
    event.preventDefault();
    if (this.settings.valid) {
      this.settingsService.save(this.settings.value);
      this.location.back();
    }
  }

  onCancel(event) {
    event.preventDefault();
    this.settings.patchValue(this.originalSettings);
    this.location.back();
  }
}

<div class="head">
  <h2 class="title mat-display-1">Settings</h2>
</div>

<div class="form-container">
  <form [formGroup]="settings" (ngSubmit)="saveSettings($event)">
    <mat-form-field>
      <mat-label>Google Translate™ API Key</mat-label>
      <input matInput formControlName="googleTranslateApiKey" id="googleTranslateApiKey">
      <mat-hint>
        <app-remote-link [href]="translateApiKeyLink">
          {{translateApiKeyLink}}
        </app-remote-link>
      </mat-hint>
    </mat-form-field>
    <div class="actions">
      <button mat-button
              color="primary"
              type="reset"
              (click)="onCancel($event)">
        Cancel
      </button>

      <button mat-raised-button color="primary" type="submit">
        Save
      </button>
    </div>
  </form>
</div>
