// src/settings/views/Settings.vue
<template>
  <v-dialog v-model="visible" fullscreen @close="hideSettings">
    <v-form @submit.prevent="handleSubmit" class="settings-form">
      <v-card class="settings">
        <v-card-title primary-title>
          <v-btn icon class="mr-2" @click="hideSettings">
            <v-icon>mdi-arrow-left</v-icon>
          </v-btn>
          Settings
        </v-card-title>

        <v-card-text>
          <v-row>
            <v-col class="px-5 pb-0">
              <v-text-field
                v-model="settings.googleTranslateApiKey"
                label="Google Translate™ API Key"
                hide-details
                outlined
              />
            </v-col>
          </v-row>
          <div class="px-2">
            <RemoteLink
              href="https://console.cloud.google.com/apis/credentials/wizard?api=translate.googleapis.com"
            />
          </div>
        </v-card-text>

        <v-spacer />

        <v-card-actions>
          <v-spacer />
          <v-btn @click="hideSettings" text>Cancel</v-btn>
          <v-btn type="submit" color="primary" class="ml-4">Save</v-btn>
          <v-spacer />
        </v-card-actions>
      </v-card>
    </v-form>
  </v-dialog>
</template>

<script lang="ts">
  import { useNamespace } from '@/store/utils';
  import { CustomSettings } from '@common/types';
  import { defineComponent, watch } from '@vue/composition-api';
  import RemoteLink from '@/components/RemoteLink.vue';

  export default defineComponent({
    name: 'Settings',
    components: {
      RemoteLink,
    },
    setup() {
      const globalModule = useNamespace('global');
      const visible = globalModule.useState<boolean>('isSettingsVisible');
      const hideSettings = globalModule.useMutation('hideSettings');

      const settingsModule = useNamespace('settings');
      const settings = settingsModule.useState<CustomSettings>('settings', { immediate: true });
      const saveSettings = settingsModule.useAction('saveSettings');

      const folderModule = useNamespace('folder');
      const refreshTranslationKey = folderModule.useAction('refreshTranslationKey');

      async function handleSubmit() {
        await saveSettings(settings.value);
        await refreshTranslationKey();
      }

      // Synchronize when the dialog is closed using ESC key
      watch(visible, () => {
        if (!visible.value) hideSettings();
      });

      return {
        visible,
        settings,
        hideSettings,
        handleSubmit,
      };
    },
  });
</script>

<style scoped lang="scss">
  .settings {
    flex: 1;
    display: flex;
    flex-direction: column;
  }

  .settings-form {
    display: flex;
    width: 100%;
    height: 100%;
  }
</style>

// renderer/settings/views/Settings.tsx
import * as React from 'react';
import Immutable from 'immutable';
import styled from 'react-emotion';
import _ from 'lodash';
import { History } from 'history';
import Form, { UiSchema } from 'react-jsonschema-form';
import { JSONSchema6 } from 'json-schema';
import { hot } from 'react-hot-loader';

import { lightBlack } from '~/lib/palette';
import RemoteLink from '~/components/RemoteLink';


const translateApiKeyLink =
  'https://console.cloud.google.com/apis/credentials/wizard?api=translate.googleapis.com';


const schema: JSONSchema6 = {
  type: 'object',
  properties: {
    googleTranslateApiKey: {
      title: 'Google Translate™ API Key',
      type: 'string',
    },
  },
};

const uiSchema: UiSchema = {
  googleTranslateApiKey: {
    'ui:help': (
      <RemoteLink
        href={translateApiKeyLink}
      >
        {translateApiKeyLink}
      </RemoteLink>
    ),
  },
};

interface IProps {
  history: History;
  settings?: Immutable.Map<string, any>;
  saveSettings: Function;
}

interface IState {
  settings?: Immutable.Map<string, any>;
}

class Settings extends React.Component<IProps, IState> {
  state: IState = {
    settings: null,
  };

  static getDerivedStateFromProps = ({ settings }: IProps, prevState: IState) =>
    !settings.equals(prevState.settings) ?
      { settings } :
      null

  handleCancel = () => {
    this.setState({
      settings: this.props.settings,
    });
  }

  handleSave = ({ formData }: any) => {
    this.props.saveSettings(formData);
  }

  render() {
    return (
      <div className="col-md-12 p-0">
        <Header>
          <BackButton
            className="btn btn-default"
            onClick={() => this.props.history.goBack()}
          >
            <i className="icon fas fa-chevron-left" />
            Back
          </BackButton>

          <HeaderTitle>
            Settings
          </HeaderTitle>
        </Header>

        <div className="d-flex justify-content-center">
          <div className="col-md-6">
            <Form
              schema={schema}
              uiSchema={uiSchema}
              formData={this.state.settings.toJS()}
              onSubmit={this.handleSave}
            >
              <div className="row col-md-12 d-flex justify-content-center">
                <button
                  className="btn btn-default mx-2"
                  type="reset"
                  onClick={this.handleCancel}
                >
                  Cancel
                </button>

                <button
                  className="btn btn-primary mx-2"
                  type="submit"
                >
                  Save
                </button>
              </div>
            </Form>
          </div>
        </div>
      </div>
    );
  }
}

export default hot(module)(Settings);

const backButtonWidth = 96;

const Header = styled('div')`
  display: flex;
`;

const BackButton = styled('button')`
  background-color: ${lightBlack.toString()};
  color: white;
  width: ${backButtonWidth}px;
  height: 48px;
  z-index: 90;

  .icon {
    margin-right: 4px;
  }
`;

const HeaderTitle = styled('h2')`
  margin-left: -${backButtonWidth}px;
  text-align: center;
  flex: 1;
`;
