// src/components/RemoteLink.tsx
import React, { useCallback } from 'react';

let shell: any = null;
if ((window as any).require) {
  shell = (window as any).require('electron').shell;
}

interface IRemoteLinkProps {
  href: string;
}

const RemoteLink: React.FC<IRemoteLinkProps> = ({children, href}) => {
  const handleClick = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
    shell.openExternal(href);
  }, [href]);

  return (
    <a href="/" onClick={handleClick}>{children || href}</a>
  );
};

export default RemoteLink;

// src/components/RemoteLink.vue
<template>
  <a href="#" @click.prevent="openLink">
    <slot>
      {{ href }}
    </slot>
  </a>
</template>

<script lang="ts">
  import { createComponent } from '@vue/composition-api';

  const shell = (window as any).require('electron').shell;

  export default createComponent({
    name: 'RemoteLink',
    props: {
      href: {
        type: String,
        required: true,
      },
    },
    setup(props) {
      function openLink() {
        shell.openExternal(props.href);
      }

      return {
        openLink,
      };
    },
  });
</script>
