// renderer/components/RemoteLink.tsx
import React from 'react';

let shell: any = null;
if (window.require) {
  shell = window.require('electron').shell;
}


const onClick = (href: string) => (e: React.MouseEvent<HTMLAnchorElement>) => {
  e.preventDefault();
  if (shell) {
    shell.openExternal(href);
  }
};

interface IProps {
  href: string;
}

const RemoteLink: React.SFC<IProps> = ({ href, children }) => (
  <a href="#" onClick={onClick(href)}>
    {children}
  </a>
);

export default RemoteLink;

// src/components/RemoteLink.vue
<template>
  <a href="#" @click.prevent="openLink">
    <slot>
      {{ href }}
    </slot>
  </a>
</template>

<script lang="ts">
  import { createComponent } from '@vue/composition-api';

  const shell = (window as any).require('electron').shell;

  export default createComponent({
    name: 'RemoteLink',
    props: {
      href: {
        type: String,
        required: true,
      },
    },
    setup(props) {
      function openLink() {
        shell.openExternal(props.href);
      }

      return {
        openLink,
      };
    },
  });
</script>
