// src/home/views/Home.vue
<template>
  <div class="home">
    <v-row>
      <v-col cols="7">
        <v-card>
          <v-card-title>Recent folders</v-card-title>

          <v-list>
            <v-list-item
              v-for="folder in recentFolders"
              :key="folder.fullPath"
              @click="openFolder(folder)"
              two-line
            >
              <v-list-item-content>
                <v-list-item-title>{{ folder.folder }}</v-list-item-title>
                <v-list-item-subtitle>{{ folder.fullPath }}</v-list-item-subtitle>
              </v-list-item-content>
            </v-list-item>
          </v-list>
        </v-card>
      </v-col>

      <v-col>
        <v-card>
          <v-card-title>Version</v-card-title>
          <v-card-text>
            <span>Current version: {{ currentVersion }}</span>
            <div v-if="latestVersion.length > 0 && currentVersion !== latestVersion">
              <strong>New version available ({{ latestVersion }})!</strong>
              &nbsp;
              <RemoteLink href="https://www.electronjs.org/apps/i18n-manager">Download</RemoteLink>
            </div>
          </v-card-text>
          <v-card-actions>
            <span>Did you like this project? Please give a star</span>
            <RemoteLink class="gh-star" href="https://github.com/gilmarsquinelato/i18n-manager">
              <svg
                viewBox="0 0 14 16"
                class="octicon octicon-star"
                style="width: 12.25px; height: 14px;"
                aria-hidden="true"
              >
                <path
                  fill-rule="evenodd"
                  d="M14 6l-4.9-.64L7 1 4.9 5.36 0 6l3.6 3.26L2.67 14 7 11.67 11.33 14l-.93-4.74L14 6z"
                />
              </svg>
              Star
            </RemoteLink>
          </v-card-actions>
        </v-card>
      </v-col>
    </v-row>
  </div>
</template>

<script lang="ts">
  import { defineComponent } from '@vue/composition-api';
  import { useNamespace } from '@/store/utils';
  import { sendIpc } from '@/store/plugins/ipc';
  import { FormattedFolderPath } from '@common/types';
  import * as ipcMessages from '@common/ipcMessages';
  import RemoteLink from '@/components/RemoteLink.vue';

  export default defineComponent({
    name: 'Home',
    components: {
      RemoteLink,
    },
    setup() {
      const homeModule = useNamespace('home');
      const recentFolders = homeModule.useState<FormattedFolderPath[]>('recentFolders');
      const checkVersion = homeModule.useAction('checkVersion');
      const currentVersion = homeModule.useState<string>('currentVersion');
      const latestVersion = homeModule.useState<string>('latestVersion');

      function openFolder(folder: FormattedFolderPath) {
        sendIpc(ipcMessages.open, folder.fullPath);
      }

      sendIpc(ipcMessages.recentFolders);
      checkVersion();

      return {
        recentFolders,
        openFolder,
        currentVersion,
        latestVersion,
      };
    },
  });
</script>

<style lang="scss">
  .home {
    padding: 0 8px;
  }

  .gh-star {
    color: #24292e !important;
    background-color: #eff3f6;
    background-image: linear-gradient(180deg, #fafbfc, #eff3f6 90%);
    border-radius: 0.25em;
    padding: 2px 5px;
    font-size: 11px;
    font-weight: 600;
    line-height: 14px;
    user-select: none;
    border: 1px solid rgba(27, 31, 35, 0.2);
    text-decoration: none;
    outline: 0;
    margin-left: 8px;

    svg {
      width: 12.25px;
      height: 14px;
      display: inline-block;
      vertical-align: text-top;
      fill: currentColor;
    }
  }
</style>

// src/home/views/Home.tsx
import { navigate, RouteComponentProps } from '@reach/router';
import { Card, Col, Layout, List, Row, Tooltip } from 'antd';
import React, { useCallback } from 'react';

import RemoteLink from '@src/components/RemoteLink';
import { actions as folderActions } from '@src/folder/store';
import { useAction, useStoreState } from '@src/store';
import { IFormattedFolderPath } from '@typings/index';
import styles from './Home.module.scss';


const RELEASES_TAG_URL = `https://github.com/gilmarsquinelato/i18n-manager/releases/tag`;

const Home: React.FC<RouteComponentProps> = () => {
  const recentFolders = useStoreState(state => state.home.recentFolders);
  const currentVersion = useStoreState(state => state.home.currentVersion);
  const latestVersion = useStoreState(state => state.home.latestVersion);

  const loadFolder = useAction(folderActions.loadFolder);

  const handleOpenFolder = useCallback(
    (e: React.MouseEvent, item: IFormattedFolderPath) => {
      e.preventDefault();

      loadFolder(item.fullPath);
      navigate('/folder');
    },
    [loadFolder]);

  return (
    <Layout className={styles.Container}>
      <Layout.Content className={styles.Content}>
        <h1 className={styles.Title}>i18n Manager</h1>

        <Row gutter={16} className={styles.CardList}>
          <Col span={12}>
            <Card title="Recent folders">
              <List
                size="small"
                dataSource={recentFolders}
                renderItem={item => (
                  <List.Item>
                    <Col span={24} className={styles.RecentFolder}>
                      <a href="/" onClick={e => handleOpenFolder(e, item)}>{item.folder}</a>
                      <Tooltip title={item.path} mouseEnterDelay={1}>
                        <span>{item.path}</span>
                      </Tooltip>
                    </Col>
                  </List.Item>
                )}
              />
            </Card>
          </Col>

          <Col span={10}>
            <Card title="Version">
              <Row>Current version: {currentVersion}</Row>
              {latestVersion.length > 0 && currentVersion !== latestVersion && (
                <Row>
                  <strong>New version available ({latestVersion})!</strong>
                  {' '}
                  <RemoteLink href={`${RELEASES_TAG_URL}/${latestVersion}`}>
                    Download
                  </RemoteLink>
                </Row>
              )}
            </Card>
          </Col>
        </Row>
      </Layout.Content>
    </Layout>
  );
};

export default Home;
